# Generated by Django 3.0.5 on 2020-07-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='addressproof',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default='', max_length=70),
        ),
    ]
